# findent from conda-forge, using findent-wrapper
- id: findent
  name: Format Fortran code using findent
  entry: findent-wrapper
  description: Uses findent from conda-forge and findent-wrapper.
  language: conda
  pass_filenames: true
  files: \.[fF](90|95|03|08)$
  types: [text]
  require_serial: false

# wfindent from conda-forge findent
- id: wfindent
  name: Format Fortran code using findent
  entry: wfindent
  description: Uses wfindent from conda-forge.
  language: conda
  pass_filenames: true
  files: \.[fF](90|95|03|08)$
  types: [text]
  require_serial: true

# system findent, using findent-wrapper
- id: findent-system
  name: Format Fortran code using findent
  entry: findent-wrapper
  description: Uses system copy of findent available on PATH and findent-wrapper.
  language: python
  pass_filenames: true
  files: \.[fF](90|95|03|08)$
  types: [text]
  require_serial: false

# system wfindent
- id: wfindent-system
  name: Format Fortran code using findent
  entry: wfindent
  description: Uses system copy of wfindent available on PATH.
  language: system
  pass_filenames: true
  files: \.[fF](90|95|03|08)$
  types: [text]
  require_serial: true

# PyPI findent, using findent-wrapper
- id: findent-pypi
  name: Format Fortran code using findent
  entry: findent-wrapper
  description: Uses findent from PyPI and findent-wrapper.
  language: python
  additional_dependencies:
    - findent
  pass_filenames: true
  files: \.[fF](90|95|03|08)$
  types: [text]
  require_serial: false

# wfindent from PyPI findent
- id: wfindent-pypi
  name: Format Fortran code using findent
  entry: wfindent
  description: Uses wfindent from PyPI.
  language: python
  additional_dependencies:
    - findent
  pass_filenames: true
  files: \.[fF](90|95|03|08)$
  types: [text]
  require_serial: true
